spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleoa_dev?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8989
  servlet:
    context-path: /

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  validity: 86400000

logging:
  level:
    root: debug

file:
  upload:
    path: uploads